apiVersion: apps/v1
kind: Deployment
metadata:
  name: capsule-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: akshayaguda/iplnodejsproject-nodejs:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://akshaya:27017/eventDB"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017

